//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.BL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expens
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Expens()
        {
            this.Transactions = new HashSet<Transaction>();
        }
    
        public long ID { get; set; }
        public Nullable<long> ExpenseTypeID { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> dtDate { get; set; }
        public string Description { get; set; }
        public Nullable<long> UserID { get; set; }
        public Nullable<long> StatusID { get; set; }
    
        public virtual ExpenseType ExpenseType { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaction> Transactions { get; set; }
        public virtual Status Status { get; set; }
    }
}
