//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.BL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShoppingInvoice
    {
        public long ID { get; set; }
        public Nullable<long> ShoppingID { get; set; }
        public Nullable<decimal> dAmount { get; set; }
        public Nullable<System.DateTime> dtDate { get; set; }
        public Nullable<long> StatusID { get; set; }
        public Nullable<long> UserID { get; set; }
        public Nullable<long> ReturnedInvoiceID { get; set; }
    
        public virtual Shopping Shopping { get; set; }
        public virtual Status Status { get; set; }
        public virtual User User { get; set; }
    }
}
