//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.BL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierDetail
    {
        public long ID { get; set; }
        public Nullable<long> SupplierID { get; set; }
        public Nullable<decimal> TotalPaid { get; set; }
        public Nullable<decimal> TotalPurchase { get; set; }
        public Nullable<decimal> TotalRemaining { get; set; }
        public Nullable<System.DateTime> dtDate { get; set; }
    
        public virtual Supplier Supplier { get; set; }
    }
}
