//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSBL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchasePayment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PurchasePayment()
        {
            this.Transactions = new HashSet<Transaction>();
        }
    
        public long ID { get; set; }
        public Nullable<long> PurchaseID { get; set; }
        public Nullable<decimal> PaidAmount { get; set; }
        public Nullable<decimal> RemainingAmount { get; set; }
        public Nullable<decimal> TotalPurchaseAmount { get; set; }
        public Nullable<long> SupplierID { get; set; }
        public Nullable<System.DateTime> dtDate { get; set; }
        public Nullable<long> UserID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaction> Transactions { get; set; }
    }
}
