//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSBL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Purchase()
        {
            this.PurchaseDetails = new HashSet<PurchaseDetail>();
        }
    
        public long ID { get; set; }
        public Nullable<long> SupplierID { get; set; }
        public Nullable<System.DateTime> dtDate { get; set; }
        public string PurchaseInvoiceNo { get; set; }
        public Nullable<int> TotalPairsQuantity { get; set; }
        public Nullable<decimal> TotalPurchaseValue { get; set; }
        public Nullable<decimal> TotalDiscountValue { get; set; }
        public Nullable<decimal> NetTotalValue { get; set; }
        public Nullable<long> UserID { get; set; }
        public Nullable<long> StatusID { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
    
        public virtual Status Status { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseDetail> PurchaseDetails { get; set; }
    }
}
