//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSBL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public long ID { get; set; }
        public Nullable<decimal> dDebit { get; set; }
        public Nullable<decimal> dCredit { get; set; }
        public Nullable<System.DateTime> dtDate { get; set; }
        public Nullable<long> PurchaseID { get; set; }
        public Nullable<long> ExpenseID { get; set; }
        public Nullable<long> UserID { get; set; }
        public Nullable<long> ShoppingID { get; set; }
        public Nullable<long> PurchasePaymentID { get; set; }
        public Nullable<long> SupplierID { get; set; }
        public Nullable<long> StatusID { get; set; }
    
        public virtual Expens Expens { get; set; }
        public virtual PurchasePayment PurchasePayment { get; set; }
        public virtual Shopping Shopping { get; set; }
        public virtual Status Status { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual User User { get; set; }
    }
}
